name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 20

jobs:
  find-samples:
    runs-on: ubuntu-latest
    outputs:
      samples: ${{ steps.list-samples.outputs.samples }}
    steps:
      - id: list-samples
        run: |
          samples=$(ls /samples | jq -R -s -c 'split("\n")[:-1]')
          echo "samples=$samples" >> $GITHUB_OUTPUT

  build_test:
    needs: find-samples
    strategy:
      matrix:
        sample: ${{ fromJSON(needs.find-samples.outputs.samples) }}

    name: ${{ matrix.sample }} - Node.js v${{ vars.NODE_VERSION }}
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js v${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Install dependencies
        run: cd samples/${{ matrix.sample }} && npm install
      - name: Build
        run: cd samples/${{ matrix.sample }} && npm run build
      - name: Lint
        run: cd samples/${{ matrix.sample }} && npm run lint --if-present
      - name: Test
        run: cd samples/${{ matrix.sample }} && npm test --if-present

  build_test_all:
    if: always()
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Check build matrix status
        if: ${{ needs.build_test.result != 'success' }}
        run: exit 1
